### ISSUE TITLE
[FORMATTING] Parse error: Ambiguous grammar

### ISSUE THREAD

**Issue by mashalzia** [sql-formatter-org/sql-formatter#561] opened 2023-02-11 13:31 UTC
BETWEEN operator with range, combined with another condition, without parenthesis is causing parse error. For example BETWEEN 25 AND 30 AND state_code = 'NY' doesn't work. BETWEEN (25 AND 30) AND state_code = 'NY' works.

**Input data**

```sql
SELECT * FROM users WHERE age BETWEEN 25 AND 35 AND state_code = 'NY'
```

**Expected Output**

```sql
SELECT
  *
FROM
  users
WHERE
  age BETWEEN 25 AND 35
  AND state_code  = 'NY'
```

**Actual Output**
Parse error: Ambiguous grammar

**Comment by nene** [comment] 2023-02-11 14:22
Thanks for reporting.

This is duplicate of #534

**Closed by nene** 2023-02-11 14:22 UTC
Labels: bug
