### ISSUE TITLE
[FORMATTING] Missing space/new line with DELIMITER

### ISSUE THREAD

**Issue by inferrinizzard** [sql-formatter-org/sql-formatter#229] opened 2022-06-08 14:36 UTC
\<Transferred from inferrinizzard/prettier-sql#72, inferrinizzard/prettier-sql#73\>

**Describe the bug**
When using a `DELIMITER` there is an erroneous output. Try to format the following code:
```
DELIMITER $$

CREATE PROCEDURE sp_name()
BEGIN
  -- statements
END $$

DELIMITER ;
```

**Expected Output**
```
DELIMITER $$
CREATE PROCEDURE sp_name()
BEGIN
    -- statements
END $$
DELIMITER ;
```

**Actual Output**
There is no new line after `BEGIN`, but most importantly there is no space or even better a new line after `END $$` and a space after `DELIMITER`.
```
DELIMITER $$
CREATE PROCEDURE sp_name()
BEGIN -- statements
END $$DELIMITER;
```

**Usage**

- How are you calling / using the script? (Please provide a code snippet, if applicable)
  `prettier-sql -l mariadb -o with_delimiter.sql with_delimiter_formatted.sql`
- What SQL language(s) does this apply to?
  MariaDB, MySQL
- What Node version?
  16

**Comment by nene** [comment] 2022-06-08 19:01
Delimiter is currently not supported. Closing this as duplicate of #184

**Closed by nene** 2022-06-08 19:01 UTC
Labels: bug
