### ISSUE TITLE
Feature Request: Add Snowflake as a SQL Dialect

### ISSUE THREAD

**Issue by gvanstee** [sql-formatter-org/sql-formatter#366] opened 2022-08-01 18:37 UTC
**Describe the Feature**
The `sql-formatter` currently supports many SQL dialects, including BigQuery and SQL Server. Would it be possible to add Snowflake?

**Why do you want this feature?**
I use Snowflake. I am particularly interested in whether the auto-formatter provided from the open source code by Snowflake, [GitHub - Snowflake-Labs/snowsql-formatter](https://github.com/Snowflake-Labs/snowsql-formatter), is materially different (in whether it will produce compilation errors) from what is provided here by `sql-formatter`.

**Comment by inferrinizzard** [comment] 2022-08-01 18:48
Duplicate of #173 
I'll make note of the consistent interest of adding Snowflake as a supported dialect.

As for the differences between this upstream library and `snowsql-formatter`, this package has had several major revisions in across all parts of the codebase in the past 6-12months so I would definitely recommend this package if it works for use cases.

We would gladly accept a PR for Snowflake as a new language if you feel up to it, please feel free to reach out to me or @nene for assistance - the main effort there would be to research/document the syntax (ie. special keywords, supported operators, string types, etc.)

**Comment by primeapple** [comment] 2022-08-02 07:09
I'm also interested in this and will have a look!

**Comment by inferrinizzard** [comment] 2022-08-02 14:04
Great, #297 is a good example of a PR with a recently added language (Trino) so you can reference that to see what changes are needed

**Comment by primeapple** [comment] 2022-09-19 13:26
Question:
For some Languages you have split the functions in categories: https://github.com/sql-formatter-org/sql-formatter/blob/master/src/languages/plsql/plsql.functions.ts#L5 (`numeric`, `character`, .etc.)

For others there is only a single category: https://github.com/sql-formatter-org/sql-formatter/blob/1d83dc245c3257ec61f4b15a63b73b1b32e63482/src/languages/trino/trino.functions.ts#L10 (`all`)

What is preferred here?  
Snowflake offers categories for functions as well, however some functions belong to multiple categories. (see https://docs.snowflake.com/en/sql-reference/functions-all.html , have a look at the `Category` column). What should be done in these cases if wemove with seperate categories?

**Comment by nene** [comment] 2022-09-19 13:50
The main reason for grouping or not grouping is to make it easier to compare with language documentation. Like when official docs of an SQL dialect have functions listed in groups, it would also be better to list them in groups in the functions list. Duplicates don't matter, the `flatKeywordList()` function eliminates duplicates.

**Comment by nene** [comment] 2022-10-04 11:24
Snowflake support is now present since version 11.0.0

**Closed by nene** 2022-10-04 11:24 UTC
Labels: help wanted, feature
