### ISSUE TITLE
[FORMATTING] VALUES not honoring multilineLists

### ISSUE THREAD

**Issue by rogerfar** [sql-formatter-org/sql-formatter#245] opened 2022-06-20 22:28 UTC
**Expected Output**

```sql
INSERT INTO
    [Approvals] (
        approvalId,
        DATE,
        approvalType,
        approvalStatus
    )
VALUES
    (7e8fec4c-060c-43b1-9db9-1002ffd1d1e5, 
	1654147984224, 
	, 
	Approved)
```

**Actual Output**

```sql
INSERT INTO
    [Approvals] (
        approvalId,
        DATE,
        approvalType,
        approvalStatus
    )
VALUES
    (7e8fec4c-060c-43b1-9db9-1002ffd1d1e5, 1654147984224, , Approved)
```

**Usage**
```
{
        language: 'sqlite',
        tabWidth: 4,
        useTabs: false,
        keywordCase: 'upper',
        indentStyle: 'standard',
        logicalOperatorNewline: 'after',
        multilineLists: 'always',
        params: parameters ?? {},
      }
```

There are a few issues here, not sure if you want me to break them into separate issues?

* The part after VALUE does not get split into multi lines
* NULL values are shown as empty, hard to see if it's an empty string or NULL
* Column names that are keywords (`DATE`) are handled as keywords, but should remain lowercase as they are column names.

**Comment by nene** [comment] 2022-06-21 06:20
> The part after VALUE does not get split into multi lines
> NULL values are shown as empty, hard to see if it's an empty string or NULL

Could you please also provide the original input string and the parameter values you're using.

Also, do bear in mind that the formatter does not do any escaping/quoting of the values you provide. 

> Column names that are keywords (DATE) are handled as keywords, but should remain lowercase as they are column names.

This is currently a known issue. The uppercasing of keywords doesn't really understand contect. #156

**Comment by rogerfar** [comment] 2022-06-21 13:24
Yes, sorry, the input is:
```sql
INSERT INTO [Approvals] (approvalId,date,approvalType,approvalStatus) VALUES (?,?,?,?)
```
with parameters:
```
0: "993aade9-afb6-4c72-bb61-35fd23244ba8"
1: 1653162334173
2: NULL
3: "Approved"
```

**Comment by nene** [comment] 2022-06-21 14:20
Was able to reproduce your exact issue with the following code:

```js
format(
  'INSERT INTO [Approvals] (approvalId,date,approvalType,approvalStatus,andSomethingLong) VALUES (?,?,?,?)',
  {
    language: 'sqlite',
    params: {
      0: '993aade9-afb6-4c72-bb61-35fd23244ba8',
      1: '1653162334173',
      2: '',
      3: 'Approved',
    },
  }
)
```

So... there are indeed multiple problems here.

### Missing NULL values

The values in `params` should really only be strings. At the moment you'll get a type error when you're using the library through TypeScript. I probably should also add at least a warning when non-string values are supplied. So instead of `NULL`, you really should use `"NULL"` string and for strings you should quote them like `"'Approved'"`.

### No line breaks between parameters

Turns out that the formatter currently only looks at the un-expanded parameter placeholders `(?,?,?,?)` and concludes that this is short enough to not need any line breaks within. But it really should consider the expanded placeholders.

That's definitely a new bug I haven't encountered before.

### Confusing behavior of the multilineLists option

I'm inclined to say that this option is currently fundamentally broken. It doesn't really do at all what it claims to do. It really only works properly for the list of columns in `SELECT` clause, and is more of a hit and miss elsewhere.

The problem is that the effect of this option (and some others) is overridden by a more general formatting rule which decides whether parenthesized expressions are short enough to be formatted without line breaks.

**Comment by nene** [comment] 2022-07-01 06:57
Closing this:

- `multilineLists` option has been deprecated (and will be removed in next major version).
- non-string values for `params` option now produce a warning (and will give an error in next major version).

**Closed by nene** 2022-07-01 06:57 UTC
Labels: bug

**Comment by nene** [comment] 2022-09-08 06:52
The long parameter value substitutions should now be formatted in a much better way in 10.6.0 release.
