### ISSUE TITLE
[FORMATTING] SQLite: This doesn't look right

### ISSUE THREAD

**Issue by Prinzhorn** [sql-formatter-org/sql-formatter#446] opened 2022-09-17 11:26 UTC
**Input data**

Couldn't think of a better title, was just going through my saved queries to see how they would be formatted.

https://sql-formatter-org.github.io/sql-formatter/ defaults with `SQLite` +  `uppercase` options

```sql
SELECT
    foo_bar.value,
    substr(
        decode(content, encoding),
        max(1, foo_bar.start - 20),
        min(length(decode(content, encoding)) - foo_bar.start, end - start + 40)
    ) AS context
FROM view_response_bodies, foo_bar(decode(content, encoding))
```

**Expected Output**

Something like this (I guess that depends on the expression width as well):

```sql
SELECT
    foo_bar.value,
    substr(
        decode(content, encoding),
        max(1, foo_bar.start - 20),
        min(
            length(decode(content, encoding)) - foo_bar.start,
            end - start + 40
        )
    ) AS context
FROM view_response_bodies, foo_bar(decode(content, encoding))
```

**Actual Output**

The comments point to the most obvious things that are broken

```sql
SELECT
  foo_bar.value,
  SUBSTR(
    decode (content, encoding), -- SUBSTR is upper case, but not my user-defined decode() function. To be fair, the docs say " and builtin function names to upper or lowercase."
    MAX(1, foo_bar.start - 20),
    MIN(
      LENGTH(decode (content, encoding)) - foo_bar.start,
    END - start + 40 -- end/start are columns of the foo_bar virtual table, don't touch them
    -- Why is this not indented?
  )
) AS context -- shouldn't this be indented one more?
FROM
  view_response_bodies,
  foo_bar (decode (content, encoding))
```

**Usage**

https://sql-formatter-org.github.io/sql-formatter/ defaults with `SQLite` +  `uppercase` options

**Comment by nene** [comment] 2022-09-17 12:51
This is another case of the formatter failing to properly distinguish between keywords and identifiers. Duplicate of #156 and #302.

All the indentation issues are just consequences of that underlying issue :(

**Comment by nene** [comment] 2022-09-17 12:51
This is another case of the formatter failing to properly distinguish between keywords and identifiers. Duplicate of #156 and #302.

All the indentation issues are just consequences of that underlying issue :(

**Comment by Prinzhorn** [comment] 2022-09-17 13:10
Looks like other tools suffer from the same issues when not using an actual SQL parser

https://sqlformat.org/
https://sqlparse.readthedocs.io/en/latest/
https://github.com/andialbrecht/sqlparse/issues/631

I was hoping we could draw some inspiration from this package, but it also makes the END/START upper case.

**Comment by nene** [comment] 2022-09-20 12:51
Closing this as duplicate.

**Closed by nene** 2022-09-20 12:51 UTC
Labels: bug
