### ISSUE TITLE
Cannot be formatted when “--” exists

### ISSUE THREAD

**Issue by lishuyi** [sql-formatter-org/sql-formatter#601] opened 2023-05-19 07:53 UTC
**Describe the bug**
1、When '--' exists at the beginning, the code is not formatted,all the code in a line;
![image](https://github.com/sql-formatter-org/sql-formatter/assets/19965480/ee3820fd-8196-4499-9d4a-18f3850fc6c0)

2、When '--' exists in code, an error is occurred;
![image](https://github.com/sql-formatter-org/sql-formatter/assets/19965480/b21c39ab-e751-4a3e-9e85-4ba629b59194)

**Expected behavior**
When at the beginning, if encountered the 'select',there has a new line; When in code, a space newline is encountered before -- and after --.
![image](https://github.com/sql-formatter-org/sql-formatter/assets/19965480/f664021f-5997-4051-a467-aa6caef7acf1)

![image](https://github.com/sql-formatter-org/sql-formatter/assets/19965480/89c6b508-94dc-46f0-a9de-030ac95ab7eb)

**Comment by nene** [comment] 2023-05-19 08:04
Unable to reproduce. The formatter does support SQL comments.

Please provide the exact input SQL you're using. And describe how exactly you're invoking the formatter (through demo website, JS API, from command line, editor plugin, etc).

**Comment by nene** [comment] 2023-05-19 09:16
The problem is that you have your query as one long line which also contains a line-comment. So all code after the start of the line-comment is considered to be a comment. Like in here:

```sql
SELECT * FROM (SELECT * FROM foo -- WHERE x > 10)
```

The parser is expecting to find a closing `)`, but doesn't, because the code ends with a comment.

In short. The code is not valid SQL.

**Comment by lishuyi** [comment] 2023-05-20 03:00
Thank you for your guidance.And I want to know If an sql statement error occurs, how do you throw a prompt on the page?

**Comment by nene** [comment] 2023-05-20 16:06
Sorry. I don't understand the question. Try to be more clear in the words you use.

I'm also closing this issue, as there appears to be no bug in here.

**Closed by nene** 2023-05-20 16:06 UTC
Labels: bug

**Comment by lishuyi** [comment] 2023-05-22 00:39
Thank you for your reply. It has been solved
