### ISSUE TITLE
Parser Error: `BETWEEN AND` in where clause crashes when closing parenthesis end at other `AND` statements

### ISSUE THREAD

**Issue by rosieyu1995** [sql-formatter-org/sql-formatter#542] opened 2022-12-14 20:48 UTC
**Describe the bug**
Raise Error:
``` sql
select * from test_table tt
LEFT JOIN test2_table t2t
on tt.id = t2t.id
where ( tt.dt between to_date('09/28/2022', 'MM/dd/yyyy') 
and to_date('10/28/2022', 'MM/dd/yyyy')
and tt.category = 'Test_Category')
```

**Expected behavior**
To format correctly without error

**Actual behavior**
An unexpected error occur
```
Uncaught Error: Parse error: Ambiguous grammar
[
  [
    {
      "type": "statement",
      "children": [
        {
          "type": "clause",
          "nameKw": {
            "type": "keyword",
            "tokenType": "RESERVED_SELECT",
            "text": "SELECT",
            "raw": "select"
          },
          "children": [
            {
              "type": "all_columns_asterisk"
            }
          ]
        },
        {
          "type": "clause",
          "nameKw": {
            "type": "keyword",
            "tokenType": "RESERVED_CLAUSE",
            "text": "FROM",
            "raw": "from"
          },
          "children": [
            {
              "type": "identifier",
              "text": "test_table"
            },
            {
              "type": "identifier",
              "text": "tt"
            },
            {
              "type": "keyword",
              "tokenType": "RESERVED_JOIN",
              "text": "LEFT JOIN",
              "raw": "LEFT JOIN"
            },
            {
              "type": "identifier",
              "text": "test2_table"
            },
            {
              "type": "identifier",
              "text": "t2t"
            },
            {
              "type": "keyword",
              "tokenType": "RESERVED_KEYWORD",
              "text": "ON",
              "raw": "on"
            },
            {
              "type": "property_access",
              "object": {
                "type": "identifier",
                "text": "tt"
              },
              "property": {
                "type": "identifier",
                "text": "id"
              }
            },
            {
              "type": "operator",
              "text": "="
            },
            {
              "type": "property_access",
              "object": {
                "type": "identifier",
                "text": "t2t"
              },
              "property": {
                "type": "identifier",
                "text": "id"
              }
            }
          ]
        },
        {
          "type": "clause",
          "nameKw": {
            "type": "keyword",
            "tokenType": "RESERVED_CLAUSE",
            "text": "WHERE",
            "raw": "where"
          },
          "children": [
            {
              "type": "parenthesis",
              "children": [
                {
                  "type": "property_access",
                  "object": {
                    "type": "identifier",
                    "text": "tt"
                  },
                  "property": {
                    "type": "identifier",
                    "text": "dt"
                  }
                },
                {
                  "type": "between_predicate",
                  "betweenKw": {
                    "type": "keyword",
                    "tokenType": "BETWEEN",
                    "text": "BETWEEN",
                    "raw": "between"
                  },
                  "expr1": [
                    {
                      "type": "identifier",
                      "text": "to_date"
                    },
                    {
                      "type": "parenthesis",
                      "children": [
                        {
                          "type": "literal",
                          "text": "'09/28/2022'"
                        },
                        {
                          "type": "comma"
                        },
                        {
                          "type": "literal",
                          "text": "'MM/dd/yyyy'"
                        }
                      ],
                      "openParen": "(",
                      "closeParen": ")"
                    },
                    {
                      "type": "keyword",
                      "tokenType": "AND",
                      "text": "AND",
                      "raw": "and"
                    },
                    {
                      "type": "identifier",
                      "text": "to_date"
                    },
                    {
                      "type": "parenthesis",
                      "children": [
                        {
                          "type": "literal",
                          "text": "'10/28/2022'"
                        },
                        {
                          "type": "comma"
                        },
                        {
                          "type": "literal",
                          "text": "'MM/dd/yyyy'"
                        }
                      ],
                      "openParen": "(",
                      "closeParen": ")"
                    }
                  ],
                  "andKw": {
                    "type": "keyword",
                    "tokenType": "AND",
                    "text": "AND",
                    "raw": "and"
                  },
                  "expr2": [
                    {
                      "type": "property_access",
                      "object": {
                        "type": "identifier",
                        "text": "tt"
                      },
                      "property": {
                        "type": "identifier",
                        "text": "category"
                      }
                    }
                  ]
                },
                {
                  "type": "operator",
                  "text": "="
                },
                {
                  "type": "literal",
                  "text": "'Test_Category'"
                }
              ],
              "openParen": "(",
              "closeParen": ")"
            }
          ]
        }
      ],
      "hasSemicolon": false
    }
  ],
  [
    {
      "type": "statement",
      "children": [
        {
          "type": "clause",
          "nameKw": {
            "type": "keyword",
            "tokenType": "RESERVED_SELECT",
            "text": "SELECT",
            "raw": "select"
          },
          "children": [
            {
              "type": "all_columns_asterisk"
            }
          ]
        },
        {
          "type": "clause",
          "nameKw": {
            "type": "keyword",
            "tokenType": "RESERVED_CLAUSE",
            "text": "FROM",
            "raw": "from"
          },
          "children": [
            {
              "type": "identifier",
              "text": "test_table"
            },
            {
              "type": "identifier",
              "text": "tt"
            },
            {
              "type": "keyword",
              "tokenType": "RESERVED_JOIN",
              "text": "LEFT JOIN",
              "raw": "LEFT JOIN"
            },
            {
              "type": "identifier",
              "text": "test2_table"
            },
            {
              "type": "identifier",
              "text": "t2t"
            },
            {
              "type": "keyword",
              "tokenType": "RESERVED_KEYWORD",
              "text": "ON",
              "raw": "on"
            },
            {
              "type": "property_access",
              "object": {
                "type": "identifier",
                "text": "tt"
              },
              "property": {
                "type": "identifier",
                "text": "id"
              }
            },
            {
              "type": "operator",
              "text": "="
            },
            {
              "type": "property_access",
              "object": {
                "type": "identifier",
                "text": "t2t"
              },
              "property": {
                "type": "identifier",
                "text": "id"
              }
            }
          ]
        },
        {
          "type": "clause",
          "nameKw": {
            "type": "keyword",
            "tokenType": "RESERVED_CLAUSE",
            "text": "WHERE",
            "raw": "where"
          },
          "children": [
            {
              "type": "parenthesis",
              "children": [
                {
                  "type": "property_access",
                  "object": {
                    "type": "identifier",
                    "text": "tt"
                  },
                  "property": {
                    "type": "identifier",
                    "text": "dt"
                  }
                },
                {
                  "type": "between_predicate",
                  "betweenKw": {
                    "type": "keyword",
                    "tokenType": "BETWEEN",
                    "text": "BETWEEN",
                    "raw": "between"
                  },
                  "expr1": [
                    {
                      "type": "identifier",
                      "text": "to_date"
                    },
                    {
                      "type": "parenthesis",
                      "children": [
                        {
                          "type": "literal",
                          "text": "'09/28/2022'"
                        },
                        {
                          "type": "comma"
                        },
                        {
                          "type": "literal",
                          "text": "'MM/dd/yyyy'"
                        }
                      ],
                      "openParen": "(",
                      "closeParen": ")"
                    }
                  ],
                  "andKw": {
                    "type": "keyword",
                    "tokenType": "AND",
                    "text": "AND",
                    "raw": "and"
                  },
                  "expr2": [
                    {
                      "type": "identifier",
                      "text": "to_date"
                    }
                  ]
                },
                {
                  "type": "parenthesis",
                  "children": [
                    {
                      "type": "literal",
                      "text": "'10/28/2022'"
                    },
                    {
                      "type": "comma"
                    },
                    {
                      "type": "literal",
                      "text": "'MM/dd/yyyy'"
                    }
                  ],
                  "openParen": "(",
                  "closeParen": ")"
                },
                {
                  "type": "keyword",
                  "tokenType": "AND",
                  "text": "AND",
                  "raw": "and"
                },
                {
                  "type": "property_access",
                  "object": {
                    "type": "identifier",
                    "text": "tt"
                  },
                  "property": {
                    "type": "identifier",
                    "text": "category"
                  }
                },
                {
                  "type": "operator",
                  "text": "="
                },
                {
                  "type": "literal",
                  "text": "'Test_Category'"
                }
              ],
              "openParen": "(",
              "closeParen": ")"
            }
          ]
        }
      ],
      "hasSemicolon": false
    }
  ]
]
```

**Usage**

- How are you calling / using the library?
https://sql-formatter-org.github.io/sql-formatter/ 
- What SQL language(s) does this apply to?
All
- Which SQL Formatter version are you using?
v12.0.3

**Comment by nene** [comment] 2022-12-15 09:13
Thanks for reporting. This is duplicate of #534

**Closed** 2022-12-15 09:13 UTC
Labels: bug
