### ISSUE TITLE
[VSCODE] PostgreSQL string concatenation operator || breaks code 

### ISSUE THREAD

**Issue by jldevezas** [sql-formatter-org/sql-formatter#313] opened 2022-07-14 09:07 UTC
**Input data**

```sql
SELECT col1 || '::' || col2;
```

**Expected Output**

No spaces between '|' characters.

```sql
SELECT
  col1 || '::' || col2;
```

**Actual Output**

Spaces added between '|' characters.

```sql
SELECT
  col1 | | '::' | | col2;
```

**Usage**

- Using through Visual Studio Code extension: Prettier SQL VSCode v1.1.1
- PostgreSQL 12/14 (PL/pgSQL)

**Comment by jldevezas** [comment] 2022-07-14 09:08
Here's another easy one. Let's make this the best SQL formatting extension for vscode! :-)

**Comment by nene** [comment] 2022-07-14 09:34
That's an issue with VSCode extension. Duplicate of #227 

SQL Formatter itself handles it just fine.

**Closed** 2022-07-14 09:35 UTC
Labels: bug, vscode
