### ISSUE TITLE
[FORMATTING] Tabulate Alias breaks after Case Statements in SELECT clause

### ISSUE THREAD

**Issue by Asanil** [sql-formatter-org/sql-formatter#547] opened 2022-12-29 10:20 UTC
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT
    COUNT(DISTINCT COLUMN_A)         AS ALIAS_A,
    SUM(COLUMN_B)     AS ALIAS_B,
    CASE
        WHEN COLUMN_C = 1 THEN 10
        WHEN COLUMN_C IN (2, 3) THEN 20
        ELSE NULL
    END AS ALIAS_C,
    COLUMN_D AS ALIAS_D,
    CAST(COLUMN_E AS DECIMAL(9, 0)) AS ALIAS_E,
    COLUMN_F AS ALIAS_F
FROM
    TABLE
;
```

**Expected Output (any one of the two)**

```sql
-- Output 1: Ignoring the length of Case Statments
SELECT
    COUNT(DISTINCT COLUMN_A)        AS ALIAS_A,
    SUM(COLUMN_B)                   AS ALIAS_B,
    CASE
        WHEN COLUMN_C = 1 THEN 10
        WHEN COLUMN_C IN (2, 3) THEN 20
        ELSE NULL
    END                             AS ALIAS_C,
    COLUMN_D                        AS ALIAS_D,
    CAST(COLUMN_E AS DECIMAL(9, 0)) AS ALIAS_E, -- longest line in the SELECT clause excluding the Case statement
    COLUMN_F                        AS ALIAS_F
FROM
    TABLE
;

-- Output 2: Considering the length of Case Statments
SELECT
    COUNT(DISTINCT COLUMN_A)            AS ALIAS_A,
    SUM(COLUMN_B)                       AS ALIAS_B,
    CASE
        WHEN COLUMN_C = 1 THEN 10
        WHEN COLUMN_C IN (2, 3) THEN 20             -- longest line in the SELECT clause including the Case statement
        ELSE NULL
    END                                 AS ALIAS_C,
    COLUMN_D                            AS ALIAS_D,
    CAST(COLUMN_E AS DECIMAL(9, 0))     AS ALIAS_E,
    COLUMN_F                            AS ALIAS_F
FROM
    TABLE
;
```

**Actual Output**

```sql
-- The aliases are not right aligned after the Case Statement
SELECT
    COUNT(DISTINCT COLUMN_A) AS ALIAS_A,
    SUM(COLUMN_B)            AS ALIAS_B,
    CASE
        WHEN COLUMN_C = 1 THEN 10
        WHEN COLUMN_C IN (2, 3) THEN 20
        ELSE NULL
    END AS ALIAS_C,
    COLUMN_D AS ALIAS_D,
    CAST(COLUMN_E AS DECIMAL(9, 0)) AS ALIAS_E,
    COLUMN_F AS ALIAS_F
FROM
    TABLE
;
```

**Present Workaround**
Format the code by removing the Case statements and then insert the statements to the code.

**Usage**

- How are you calling / using the library?
  VSCode
- What SQL language(s) does this apply to?
  spark - but it seems to be case with all the other languages.
- Which SQL Formatter version are you using?
  Prettier SQL VSCode - v1.5.0

**Comment by nene** [comment] 2022-12-29 10:42
Thanks for reporting. This is sort of known issue, as the implementation of this whole `tabulateAlias` feature is problematic, [as also mentioned in documentation](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/tabulateAlias.md).

Unfortunately there's no easy way to fix this (it would need a complete rewrite, and likely a larger redesign of the whole SQL formatter library). I've opted to keep this feature in its buggy form rather than completely deleting it.

I'm closing this issue as it's essentially a duplicate of #236 (though it might not look like so on the surface).

**Closed by nene** 2022-12-29 10:42 UTC
Labels: bug

**Comment by Asanil** [comment] 2022-12-29 11:05
Thank you! It's just a minor workaround and I can live with it 😄
