### ISSUE TITLE
[FORMATTING] Snowflake - BETWEEN causes error in output

### ISSUE THREAD

**Issue by jgontarz** [sql-formatter-org/sql-formatter#538] opened 2022-12-07 17:24 UTC
Which SQL and options did you provide as input?

Language = Snowflake
Everything else left as default option.

**Raises Error:**
```sql
select
    "Col1"
   ,"Col2"
   ,"Col3"
from SourceDataset
 where "Col1" between '10-28-2022'::date and '10-20-2022'::date and "Col2" = 23
```

**Expected Output**
```sql
select
  "Col1",
  "Col2",
  "Col3"
from
  SourceDataset
where
  "Col1" between '10-28-2022'::date and '10-20-2022'::date
  and "Col2" = 23
```

**Actual Output**

`An Unexpected Error Occurred
Parse error: Ambiguous grammar [ [ { "type": "statement", "children": [ { "type": "clause", "nameKw": { "type": "keyword", "tokenType": "RESERVED_SELECT", "text": "SELECT", "raw": "select" }, "children": [ { "type": "identifier", "text": "\"Col1\"" }, { "type": "comma" }, { "type": "identifier", "text": "\"Col2\"" }, { "type": "comma" }, { "type": "identifier", "text": "\"Col3\"" } ] }, { "type": "clause", "nameKw": { "type": "keyword", "tokenType": "RESERVED_CLAUSE", "text": "FROM", "raw": "from" }, "children": [ { "type": "identifier", "text": "SourceDataset" } ] }, { "type": "clause", "nameKw": { "type": "keyword", "tokenType": "RESERVED_CLAUSE", "text": "WHERE", "raw": "where" }, "children": [ { "type": "identifier", "text": "\"Col1\"" }, { "type": "between_predicate", "betweenKw": { "type": "keyword", "tokenType": "BETWEEN", "text": "BETWEEN", "raw": "between" }, "expr1": [ { "type": "literal", "text": "'10-28-2022'" }, { "type": "operator", "text": "::" }, { "type": "keyword", "tokenType": "RESERVED_KEYWORD" ... `

**Usage**

- How are you calling / using the library?
I am using this through Chrome - https://sql-formatter-org.github.io/sql-formatter/.

- What SQL language(s) does this apply to?
Snowflake is all I have tried.

- Which SQL Formatter version are you using?
v12.0.3

**Comment by nene** [comment] 2022-12-07 21:32
Thanks for reporting. This is duplicate of #534

**Closed by nene** 2022-12-07 21:32 UTC
Labels: bug
