### ISSUE TITLE
[FORMATTING] Empty lines between comment lines/blocks should be preserved

### ISSUE THREAD

**Issue by regexident** [sql-formatter-org/sql-formatter#772] opened 2024-08-29 22:26 UTC
**Input data**

Which SQL and options did you provide as input?

I'm using the default settings of "Prettier SQL VSCode".

sql-formatter strips empty lines between line/block comment sections, fusing the sections together,
which is highly undesirable if those comment sections are unrelated and just happen to not have any code in between them.

This behavior is particularly unfortunate for code that makes use of [minimap section header](https://code.visualstudio.com/updates/v1_88#_minimap-section-headers) comments like this:

```sql
-- MARK: Section name

/* MARK: Section name */
```

… which get dissolved into whatever other comments happen to surround it, despite being clearly a separate "thing".

At the very least I would expect sql-formatter to expose a configuration option for preserving gaps between comment blocks.

```sql
-- MARK: Tables

-- Some free-standing comment block providing some
-- more broad discussion on the code surrounding it
-- without being attached to a specific code

-- Some comment describing the `foo` view
--
-- With maybe even a block and some more details
-- about the why, the what, and the how.
CREATE TABLE IF NOT EXISTS maybe_foo (/* ... */);

/* MARK: Views */

/*
 Some free-standing comment block providing some
 more broad discussion on the code surrounding it
 without being attached to a specific code
 */

/*
 Some comment describing the `foo` view

 With maybe even a block and some more details
 about the why, the what, and the how.
 */
CREATE VIEW IF NOT EXISTS foo AS
SELECT /* ... */ FROM maybe_foo
WHERE NOT is_deleted;
```

**Expected Output**

```sql
-- MARK: Tables

-- Some free-standing comment block providing some
-- more broad discussion on the code surrounding it
-- without being attached to a specific code

-- Some comment describing the `foo` view
--
-- With maybe even a block and some more details
-- about the why, the what, and the how.
CREATE TABLE
    IF NOT EXISTS maybe_foo (/* ... */);

/* MARK: Views */

/*
Some free-standing comment block providing some
more broad discussion on the code surrounding it
without being attached to a specific code
 */

/*
Some comment describing the `foo` view

With maybe even a block and some more details
about the why, the what, and the how.
 */
CREATE VIEW
    IF NOT EXISTS foo AS
SELECT
    /* ... */
FROM
    maybe_foo
WHERE
    NOT is_deleted;
```

**Actual Output**

```sql
-- MARK: Tables
-- Some free-standing comment block providing some
-- more broad discussion on the code surrounding it
-- without being attached to a specific code
-- Some comment describing the `foo` view
--
-- With maybe even a block and some more details
-- about the why, the what, and the how.
CREATE TABLE
    IF NOT EXISTS maybe_foo (/* ... */);

/* MARK: Views */
/*
Some free-standing comment block providing some
more broad discussion on the code surrounding it
without being attached to a specific code
 */
/*
Some comment describing the `foo` view

With maybe even a block and some more details
about the why, the what, and the how.
 */
CREATE VIEW
    IF NOT EXISTS foo AS
SELECT
    /* ... */
FROM
    maybe_foo
WHERE
    NOT is_deleted;
```

**Usage**

- How are you calling / using the library?

In VSCode via the [inferrinizzard.prettier-sql-vscode](https://marketplace.visualstudio.com/items?itemName=inferrinizzard.prettier-sql-vscode) extension.

- What SQL language(s) does this apply to?

I'm using PGSQL, but it should apply to all supported dialects, I presume.

- Which SQL Formatter version are you using?

Whatever version shipped with Prettier SQL VSCode v1.6.0.

**Comment by nene** [comment] 2024-09-01 18:33
Thanks for the suggestion. This is definitely an area where SQL Formatter lacks (among many things).

However, even when this feature gets implemented in SQL Formatter, it will likely never reach the plugin you're using, because it's no longer maintained. [See the FAQ](https://github.com/sql-formatter-org/sql-formatter?tab=readme-ov-file#im-having-a-problem-with-prettier-sql-vscode-extension)

This particular problem has been solved in [prettier-plugin-sql-cst](https://github.com/nene/prettier-plugin-sql-cst). Which is another SQL formatting tool I've written to overcome the fundamental shortcomings of SQL Formatter. It doesn't yet have full PostgreSQL support, but perhaps enough for your use.

Regarding implementing this in SQL Formatter.. well, I'm not really doing any new feature development in here. So the chances of it happening are pretty low.

**Comment by nene** [comment] 2024-10-24 14:22
Closing this as it's a duplicate of a very old feature request: #329

**Closed by nene** 2024-10-24 14:22 UTC
Labels: feature
