### ISSUE TITLE
[FORMATTING] Issue while trying to format sql file with special character inside

### ISSUE THREAD

**Issue by KurayamiNoDaiTenshi** [sql-formatter-org/sql-formatter#514] opened 2022-11-04 09:49 UTC
**Input data**

Which SQL and options did you provide as input?

```sql
SELECT c.name FROM customer c WHERE c.customer_ID = {{id?0}}
```

**Expected Output**

```sql
SELECT
  c.name
FROM 
  customer c
WHERE
c.customer_ID = {{id?0}}
```

**Actual Output**

none got an error telling me there is an unexpected token near {{id?0}} 

**Usage**
We are using a framework who will replace all '{{parameter}}' string with the equivalent value.
We just want to ability to tell to the extension to ignore regex string like \{.*\}
- How are you calling / using the library?
  - vscode extension
- What SQL language(s) does this apply to?
  - all
- Which SQL Formatter version are you using?
  - 1.4.0

**Comment by nene** [comment] 2022-11-04 10:45
This is essentially a duplicate of #503

**Closed by nene** 2022-11-04 10:45 UTC
Labels: bug
