### ISSUE TITLE
Slow save

### ISSUE THREAD

**Issue by Notaduck** [sql-formatter-org/sql-formatter#665] opened 2023-11-14 13:36 UTC
Type: <b>Bug</b>

takes a long time to save a file when this extension are used, up to 5-8 seconds.

Extension version: 1.6.0
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:52:33.687Z)
OS version: Darwin x64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|11, 6, 4|
|Memory (System)|16.00GB (0.55GB free)|
|Process Argv|./ --crash-reporter-id 0b2e0296-2593-4cf2-8761-5b95a84171b1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30887144
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30886140
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016cf:30886111
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by nene** [comment] 2023-11-14 13:57
Thanks for reporting.

First off, I assume from your reported version number that you're using the "Prettier SQL VSCode" extension. This extension is no more maintained by its author and there's nothing I can do about it. I suggest you instead try the [SQL Formatter VSCode](https://marketplace.visualstudio.com/items?itemName=ReneSaarsoo.sql-formatter-vsc) extension.

I haven't experienced any performance issues with this either extension though. Perhaps you could be more specific:

- Does the saving of any file in VSCode get slow or does it only effect SQL files?
- Are you perhaps working with large files? How large?

I have absolutely no idea what this "A/B Experiments" that is that you have provided.

**Comment by nene** [comment] 2023-11-15 13:08
Given no further details I'm closing this as: Unable to reproduce.

**Closed by nene** 2023-11-15 13:08 UTC

**Comment by Notaduck** [comment] 2023-11-21 12:06
> Given no further details I'm closing this as: Unable to reproduce.

I think your explanation was clear ;) The A/B experients and so on was provided by VS codes `Start Extension Bisect` tool.
