### ISSUE TITLE
Formatting Error with Temporary Functions

### ISSUE THREAD

**Issue by dmill166** [sql-formatter-org/sql-formatter#739] opened 2024-04-30 19:52 UTC
Issue is with use of temporary function in SQL scripts. I illustrate the problem below. You can see that in the formatted result, there is now a space between foo_bar and the left parentheses `(`. This is no longer treated as a function and the function itself is no longer applied.
I also provide a corrected output where after formatting, the temporary function `foo_bar` has the `(` immediately beside it (meaning the function will now be applied).

Which SQL and options did you provide as input?

```sql
CREATE TEMPORARY FUNCTION foo_bar AS 'FooBar' USING jar 'hdfs://localhost:9000/user/hive/FooBar.jar';

SELECT    foo_bar ('fwfrgwre12a3') fun_res ;
```

**Expected Output**

```sql
CREATE TEMPORARY FUNCTION foo_bar AS 'FooBar' USING jar 'hdfs://localhost:9000/user/hive/FooBar.jar';

SELECT
    foo_bar('fwfrgwre12a3') fun_res;
```

**Actual Output**

```sql
CREATE TEMPORARY FUNCTION foo_bar AS 'FooBar' USING jar 'hdfs://localhost:9000/user/hive/FooBar.jar';

SELECT
    foo_bar ('fwfrgwre12a3') fun_res;
```

**Usage**

- How are you calling / using the library?
  - Right-click, then use "Format Document" option
- What SQL language(s) does this apply to?
  - Specific example was a .hql extension, but multiple SQL variants support Temporary Functions, so this should be widely implemented
- Which SQL Formatter version are you using?
  - Prettier SQL VSCode v1.6.0

**Comment by dmill166** [comment] 2024-04-30 20:10
Perusing the README, I did see that there is a successor to this extension, SQL Formatter VS Code (currently on v4.1.1).
![image](https://github.com/sql-formatter-org/sql-formatter/assets/70177994/94d00df5-5ce1-43e3-bae9-5b6cd6bb1847)

I want to clarify that this issue ALSO exists there (would appreciate a fix in either/both locs :) ).

**Comment by nene** [comment] 2024-05-02 08:21
Thanks for reporting.

This is duplicate of #444. It's a known problem with all user-defined functions (not just temporary ones).

**Closed by nene** 2024-05-02 08:21 UTC
Labels: bug
